// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8S7RgMHW6ziWX6yuZWjpjku3CcNG5Ho',
    appId: '1:1011075237640:web:dbff160f4871eab6eb8ebd',
    messagingSenderId: '1011075237640',
    projectId: 'kavach-2368e',
    authDomain: 'kavach-2368e.firebaseapp.com',
    databaseURL: 'https://kavach-2368e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kavach-2368e.appspot.com',
    measurementId: 'G-3M6TVGVF5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKR3yjvAF_ezNB0yxwW66Co6x5M97efvA',
    appId: '1:1011075237640:android:431c2925ebf69faceb8ebd',
    messagingSenderId: '1011075237640',
    projectId: 'kavach-2368e',
    databaseURL: 'https://kavach-2368e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kavach-2368e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2V4AcO6UnsdNlD5gpiqN36dfOPBn_GDw',
    appId: '1:1011075237640:ios:88b8bae83f78b55aeb8ebd',
    messagingSenderId: '1011075237640',
    projectId: 'kavach-2368e',
    databaseURL: 'https://kavach-2368e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kavach-2368e.appspot.com',
    iosClientId: '1011075237640-3nemp8id7sof4ljd3htppnrtm97k3r9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2V4AcO6UnsdNlD5gpiqN36dfOPBn_GDw',
    appId: '1:1011075237640:ios:88b8bae83f78b55aeb8ebd',
    messagingSenderId: '1011075237640',
    projectId: 'kavach-2368e',
    databaseURL: 'https://kavach-2368e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kavach-2368e.appspot.com',
    iosClientId: '1011075237640-3nemp8id7sof4ljd3htppnrtm97k3r9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach13',
  );
}
